[versions]
dokka = "2.2.0"
guava = "33.6.0-jre"
junit4 = "4.13.2"
# don't upgrade to Kotlin 2.4 until Hilt > 2.59.2 fixes the metadata problem (https://github.com/google/dagger/issues/5177)
kotlin = "2.4.10"
kotlin-coroutines = "1.11.0"
spotbugs = "4.10.3"
xpp3Version = "1.1.6"
ktor = "3.5.2"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }
xpp3 = { module = "org.ogce:xpp3", version.ref = "xpp3Version" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
